DROP TABLE BOARD;
CREATE TABLE BOARD(
    BOARD_NO NUMBER(10) PRIMARY KEY,
    BOARD_DATE DATE NOT NULL,
    BOARD_TITLE VARCHAR2(255) NOT NULL,
    BOARD_CONTENT VARCHAR2(4000) NOT NULL);
    
DROP SEQUENCE BOARD_NO_SEQ;
CREATE SEQUENCE BOARD_NO_SEQ INCREMENT BY 1 START WITH 1;

COMMIT;
ROLLBACK;

DESC BOARD;

INSERT INTO BOARD VALUES(BOARD_NO_SEQ.NEXTVAL, SYSDATE, '제목', '내용');
DELETE FROM BOARD WHERE BOARD_NO = 4;
UPDATE BOARD SET BOARD_TITLE = '제목2', BOARD_CONTENT = '내용2' WHERE BOARD_NO = 3;
SELECT * FROM BOARD WHERE BOARD_NO = 3;
SELECT * FROM BOARD ORDER BY BOARD_NO DESC;

SELECT COUNT(*) FROM BOARD;


SELECT BOARD_NO, BOARD_DATE, BOARD_TITLE, BOARD_CONTENT
FROM
    (
        SELECT *
        FROM 
        (
            SELECT ROW_NUMBER() OVER (ORDER BY BOARD_NO DESC) AS SEQ, BOARD.*
            FROM BOARD
        )
        WHERE SEQ <= 5
    )
WHERE SEQ >=3;

SELECT COUNT(*) FROM BOARD;