DROP TABLE TTT;
CREATE TABLE TTT(
	TTT_NO NUMBER(10) PRIMARY KEY,
	TTT_DRAW VARCHAR2(1) NOT NULL,
	TTT_ROW NUMBER(1) NOT NULL,
	TTT_COL NUMBER(1) NOT NULL,
	TTT_SESSIONID VARCHAR2(15) NOT NULL);

DROP SEQUENCE TTT_NO_SEQ;
CREATE SEQUENCE TTT_NO_SEQ INCREMENT BY 1 START WITH 1;

CREATE INDEX TTT_IDX1 ON TTT(TTT_SESSIONID,TTT_DRAW,TTT_ROW);
CREATE INDEX TTT_IDX2 ON TTT(TTT_SESSIONID,TTT_DRAW,TTT_COL);
CREATE INDEX TTT_IDX3 ON TTT(TTT_SESSIONID);


DELETE FROM TTT;

SELECT COUNT(*) FROM TTT;

-- 가로
SELECT COUNT(*) FROM TTT WHERE TTT_DRAW = 'X' AND TTT_ROW = 0;

-- 세로
SELECT COUNT(*) FROM TTT WHERE TTT_DRAW = 'O' AND TTT_COL = 0;

-- 대각선
SELECT COUNT(*) FROM TTT WHERE TTT_DRAW = 'X' AND TTT_COL = TTT_ROW;

-- 역대각선
SELECT COUNT(*) FROM TTT WHERE TTT_DRAW = 'X' AND TTT_COL + TTT_ROW = 2;

COMMIT;
ROLLBACK;